"use client";
import { useCallback, useEffect, useMemo, useState } from 'react';
import { BookOpen, Layers, Shuffle, Settings2, ArrowRight, Check, Search, Download, FileText, CircleHelp, LoaderCircle, X, CheckCheck, AlertCircle, LibraryBig } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Progress } from '@/components/ui/progress';
import { Input } from '@/components/ui/input';
import ArticleReader, { spellingForms } from '@/components/article-reader';
import { Textarea } from '@/components/ui/textarea';

type Word = {id:string;word:string;meaning:string;review:boolean;raw:string;status:string;selectedCount:number;occurrences:number;roundCount:number;lastSeen:string|null};
type Article = {id:string;title:string;body:string;wordCount:number;counts:Record<string,number>;issues:string[];copied:boolean};
type Round = {id:string;number:number;createdAt:string;status:string;words:Pick<Word,'id'|'word'|'meaning'>[];articles:Article[];oldCount:number;error:string;mode:string;requests:{id:string;status:string;wordIds:string[];payload:unknown;response?:unknown}[];stopRequested?:boolean};
type State = {words:Word[];rounds:Round[];source:string;config:{baseUrl:string;model:string;hasKey:boolean}};
const statuses:Record<string,string>={new:'未练习',seen:'已接触',review:'待复习',mastered:'已掌握'};
const roundStatuses:Record<string,string>={generating:'生成中',complete:'已完成',needs_attention:'待补充 / 检查',interrupted:'已中断'};
type ApiResponses = {state:State;select:{ids:string[];oldCount:number;requested:number};round:{id:string};config:{ok:boolean};word:{ok:boolean};copied:{ok:boolean};stop:{ok:boolean};continue:{id:string};export:unknown};
async function api<K extends keyof ApiResponses>(path:K,data?:unknown):Promise<ApiResponses[K]> {
 const res=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json','X-Local-App':'vocab'},body:data===undefined?undefined:JSON.stringify(data)});
 const body=await res.json() as ApiResponses[K] & {error?:string}; if(!res.ok) throw new Error(body.error||'请求失败'); return body;
}
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:[string,string][];label:string}) {
 return <Select value={value} onValueChange={v=>v!==null&&onChange(v)}><SelectTrigger aria-label={label}><SelectValue>{options.find(x=>x[0]===value)?.[1]}</SelectValue></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>;
}
export default function Home(){
 const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [tab,setTab]=useState('reading'),[activeId,setActiveId]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const [count,setCount]=useState(30),[ratio,setRatio]=useState(40),[start,setStart]=useState(1),[end,setEnd]=useState(5640);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0);
 const [settings,setSettings]=useState(false),[baseUrl,setBaseUrl]=useState('https://api.deepseek.com'),[model,setModel]=useState('deepseek-v4-flash'),[key,setKey]=useState('');
 const [editing,setEditing]=useState<Word|null>(null),[editWord,setEditWord]=useState(''),[editMeaning,setEditMeaning]=useState('');
 const refresh=useCallback(async()=>{const s:State=await api('state');setData(s);return s;},[]);
 useEffect(()=>{let alive=true;api('state').then((s:State)=>{if(!alive)return;setData(s);setBaseUrl(s.config.baseUrl);setModel(s.config.model);if(s.rounds.length)setActiveId(s.rounds[s.rounds.length-1].id);return api('select',{count:30,oldPercent:40,start:1,end:9999});}).then(s=>{if(alive&&s)setSelected(s.ids);}).catch(e=>setError('无法连接本地服务：'+e.message));return()=>{alive=false;};},[]);
 const generating=Boolean(data?.rounds.some(r=>r.status==='generating'));
 useEffect(()=>{if(!generating)return;const t=setInterval(()=>refresh().catch(e=>setError(e.message)),4000);return()=>clearInterval(t);},[generating,refresh]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}};
 const words=data?.words||[];
 const dictionary=useMemo(()=>new Map((data?.words||[]).filter(w=>!w.review).flatMap(w=>spellingForms(w.word).map(f=>[f.toLowerCase(),w] as const))),[data?.words]);
 const selectedWords=useMemo(()=>selected.map(id=>words.find(w=>w.id===id)).filter(Boolean) as Word[],[selected,words]);
 const oldCount=selectedWords.filter(w=>w.occurrences>0).length;
 const current=data?.rounds.find(r=>r.id===activeId);
 const covered=new Set(current?.articles.flatMap(a=>Object.keys(a.counts).filter(id=>a.counts[id]>0))||[]);
 const allSeen=words.filter(w=>w.occurrences>0).length;
 const mastered=words.filter(w=>w.status==='mastered').length;
 const pending=words.filter(w=>w.review).length;
 const eligible=words.length-pending;
 const visible=useMemo(()=>words.filter(w=>(!query||[w.word,w.meaning,w.id].some(t=>t.toLowerCase().includes(query.toLowerCase())))&&(filter==='all'||(filter==='pending'?w.review:filter==='selected'?selected.includes(w.id):!w.review&&w.status===filter))),[words,query,filter,selected]);
 const choose=()=>run(async()=>{const r=await api('select',{count,oldPercent:ratio,start,end});setSelected(r.ids);setNotice(`已选 ${r.ids.length} 词：旧词 ${r.oldCount}，新词 ${r.ids.length-r.oldCount}。${r.ids.length<count?'可用词不足，已选中全部可用词。':''}`);});
 const generate=(same=false)=>run(async()=>{if(!data?.config.hasKey){setSettings(true);setNotice('填写 API Key 后即可生成；尚未调用 API。');return;}const r=await api('round',same?{mode:'same',parentId:activeId}:{mode:'mixed',ids:selected});await refresh();setActiveId(r.id);setTab('reading');});
 const toggle=(id:string,checked:boolean)=>{setSelected(prev=>checked?prev.includes(id)?prev:[...prev,id]:prev.filter(v=>v!==id));};
 const wordState=(w:Word,status:string)=>run(async()=>{await api('word',{id:w.id,status});await refresh();});
 const download=()=>run(async()=>{const json=await api('export');const url=URL.createObjectURL(new Blob([JSON.stringify(json,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`四级学习档案-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);setNotice('已导出词库、状态和全部轮次；不包含 API Key。');});
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;
  const life=new AbortController();try{context.registerTool({name:'stage_vocabulary_selection',title:'准备本轮词表',description:'按新旧比例准备词表并显示在界面中，不调用模型，不产生用量。',inputSchema:{type:'object',properties:{count:{type:'integer',minimum:1,maximum:90},oldPercent:{type:'integer',minimum:0,maximum:100}},required:['count','oldPercent'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{count:number;oldPercent:number})=>{if(!Number.isInteger(input.count)||!Number.isInteger(input.oldPercent))throw Error('参数必须为整数');const r=await api('select',{...input,start:1,end:9999});setCount(input.count);setRatio(input.oldPercent);setSelected(r.ids);return{selectedIds:r.ids,oldCount:r.oldCount};}},{signal:life.signal});}catch{/* Optional browser support. */}return()=>life.abort();
 },[]);
 return <div className="app-shell">
  <aside className="rail">
   <a className="brand" href="/" aria-label="词间首页"><span className="brand-icon"><BookOpen size={23}/></span><span>词间<small>WORDS IN CONTEXT</small></span></a>
   <div className="rail-heading">我的阅读档案 <span>{data?.rounds.length||0}</span></div>
   <Button className="new-round" variant="outline" onClick={()=>{setActiveId('');setTab('reading');}}><Layers size={16}/> 准备新一轮 <span>＋</span></Button>
   <nav className="round-nav" aria-label="历史轮次">{data?.rounds.length?data.rounds.slice().reverse().map(r=><button key={r.id} className={r.id===activeId?'round-link active':'round-link'} onClick={()=>{setActiveId(r.id);setTab('reading');}}><span className="round-number">{String(r.number).padStart(2,'0')}</span><span><b>第 {r.number} 轮</b><small>{r.words.length} 词 · {r.articles.length} 篇短文</small></span><span className={'dot '+r.status}/></button>):<p className="rail-empty">你的第一篇故事<br/>即将从这里开始。</p>}</nav>
   <div className="rail-footer"><span className="local-dot"/> 本地学习空间<p>短文与进度保存在这台电脑</p><Button variant="ghost" onClick={download} disabled={busy||!data}><Download size={15}/> 导出学习档案</Button></div>
  </aside>
  <div className="workspace">
   <header className="topbar"><div className="breadcrumb">学习空间 <span>/</span> 四级大纲词表</div><Button variant="outline" onClick={()=>setSettings(true)}><Settings2 size={16}/> API 设置 <span className={'connection '+(data?.config.hasKey?'ready':'')}>{data?.config.hasKey?'已配置':'待配置'}</span></Button></header>
   <main className="main-content">
    <div className="page-heading"><div><p className="eyebrow">CET-4 · READING PRACTICE</p><h1>每一轮，都读懂更多。</h1><p className="subtitle">选一组词，读一段故事，再用全新的语境复习。</p></div><span className="source-tag"><LibraryBig size={17}/> 四级大纲词表（收藏级）</span></div>
    <div className="metrics"><div><span>词库可练习</span><strong>{eligible.toLocaleString()}<small> / {words.length.toLocaleString()}</small></strong><p>{pending.toLocaleString()} 条待核对</p></div><div><span>已在语境中接触</span><strong>{allSeen.toLocaleString()}<small> 词</small></strong><Progress value={eligible?Math.min(100,allSeen/eligible*100):0} aria-label="词汇接触进度"/></div><div><span>累计阅读素材</span><strong>{data?.rounds.reduce((n,r)=>n+r.articles.length,0)||0}<small> 篇</small></strong><p>{data?.rounds.length||0} 轮完整留档</p></div><div><span>我确认已掌握</span><strong>{mastered}<small> 词</small></strong><p>掌握程度由你确认</p></div></div>
    {error&&<div className="message error" role="alert"><AlertCircle size={18}/><span>{error}</span><Button variant="ghost" size="icon" aria-label="关闭错误提示" onClick={()=>setError('')}><X/></Button></div>}
    {notice&&<div className="message" role="status"><Check size={18}/><span>{notice}</span></div>}
    {!data&&<div className="message"><LoaderCircle className="spin"/> 正在读取本地词库… <Button variant="outline" onClick={()=>run(async()=>{await refresh();})}>重新连接</Button></div>}
    <Tabs value={tab} onValueChange={v=>setTab(String(v))}>
     <div className="tab-row"><TabsList variant="line"><TabsTrigger value="reading"><BookOpen/> 轮次阅读</TabsTrigger><TabsTrigger value="vocabulary"><LibraryBig/> 词库与状态</TabsTrigger></TabsList><span className="small-note"><span className="local-dot"/> 文件自动保存</span></div>
     <TabsContent value="reading">
      <div className="reading-layout">
       <section className="reading-column">
        {current?<>
         <div className="section-heading"><div><p className="eyebrow">ROUND {String(current.number).padStart(2,'0')}</p><h2>第 {current.number} 轮 · {current.mode==='same'?'同批词，全新故事':'新的阅读练习'}</h2></div><span className={'badge '+(current.status==='complete'?'green':'')}>{roundStatuses[current.status]}</span></div>
         <div className="round-summary"><span>{current.words.length} 目标词</span><span>{current.oldCount} 旧词 / {current.words.length-current.oldCount} 新词</span><span>旧词占 {Math.round(current.oldCount/current.words.length*100)}%</span><span>覆盖 {covered.size}/{current.words.length}</span><time>{new Date(current.createdAt).toLocaleDateString('zh-CN')}</time></div>
         {current.status==='generating'&&<div className="message"><LoaderCircle className="spin"/><span>正在逐篇生成，已保留 {current.articles.length} 篇。可以切换页面，任务会继续。</span><Button variant="outline" disabled={busy||current.stopRequested} onClick={()=>run(async()=>{await api('stop',{id:current.id});await refresh();})}>{current.stopRequested?'将在本篇结束后暂停':'本篇后暂停'}</Button></div>}
         {current.error&&<div className="message error"><AlertCircle size={18}/>{current.error}</div>}
         {current.articles.map((a,i)=><article className="story-card" key={a.id}><div className="story-meta"><span>READING {String(i+1).padStart(2,'0')}</span><span>{a.wordCount} WORDS · 目标词 {Object.values(a.counts).filter(n=>n>0).length} 个</span></div><h3>{a.title}</h3><ArticleReader articleId={a.id} body={a.body} targets={current.words} dictionary={dictionary}/>{a.issues.length>0&&<div className="article-issues">{a.issues.map((issue,j)=><p key={j}><AlertCircle size={14}/>{issue}</p>)}</div>}<div className="glossary"><h4>本篇词汇注释 <span>按实际正文匹配 · 悬停高亮词也可查看释义</span></h4><div className="glossary-grid">{current.words.filter(w=>a.counts[w.id]>0).map(w=><div key={w.id}><strong>{w.word}<small>×{a.counts[w.id]}</small></strong><span>{w.meaning}</span></div>)}</div></div><label className="copy-check"><Checkbox checked={a.copied} disabled={busy} onCheckedChange={v=>run(async()=>{await api('copied',{id:current.id,articleId:a.id,copied:!!v});await refresh();})}/><span>{a.copied?'已完成全文抄写':'读完后，完整抄写这篇短文，再勾选完成'}</span>{a.copied&&<CheckCheck size={17}/>}</label></article>)}
         {current.status!=='generating'&&<div className="round-end"><strong>每读懂一个句子，都是在向四级更进一步。</strong><p>本轮实际使用 <b>{covered.size}</b> 个目标词，共出现 {current.articles.reduce((n,a)=>n+Object.values(a.counts).reduce((x,y)=>x+y,0),0)} 次。{current.status==='complete'?'本轮目标词已全部覆盖，篇幅检查通过。':'本轮仍有内容需要补充或检查。'}</p>{covered.size<current.words.length&&<><p className="missing-words">未覆盖：{current.words.filter(w=>!covered.has(w.id)).map(w=>w.word).join(' · ')}</p><Button variant="outline" disabled={busy||generating} onClick={()=>run(async()=>{await api('continue',{id:current.id});await refresh();})}>补写遗漏词 / 继续本轮</Button></>}<Button disabled={busy||generating} onClick={()=>generate(true)}><Shuffle size={16}/> 同批再练 · 下一轮</Button></div>}
         <details className="audit"><summary>查看本轮输入与请求记录 <span>{current.requests.length} 次请求</span></summary><p>输入顺序：{current.words.map(w=>w.word).join(' → ')}</p>{current.requests.map((r,i)=><details key={r.id}><summary>请求 {i+1} · {r.wordIds.length} 词 · {r.status}</summary><pre>{JSON.stringify(r,null,2)}</pre></details>)}</details>
        </>:<div className="welcome-card"><div className="welcome-kicker"><BookOpen size={19}/> 第一轮，从一小组词开始</div><h2>先让单词有一个<br/><em>可以记住的故事。</em></h2><p>右侧已为你准备选词方案。每约 10 个目标词生成一篇 150–200 词短文，不必一次读完整本词表。</p><div className="practice-steps"><div><b>01</b><strong>读懂语境</strong><span>通过故事线索理解高亮词</span></div><div><b>02</b><strong>完整抄写</strong><span>在句子中熟悉表达和拼写</span></div><div><b>03</b><strong>打乱重编</strong><span>同一批单词，换一个新故事</span></div></div><div className="empty-note"><FileText size={18}/><span>生成后，每一篇短文、词汇注释和抄写状态都会保留在左侧轮次档案中。</span></div></div>}
       </section>
       <aside className="selection-card"><div className="selection-header"><span className="eyebrow">NEXT READING</span><h2>准备一组词</h2><p>少量新词，持续复习。</p></div><div className="form-row"><label>每轮目标词数<Input type="number" min={1} max={90} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label>旧词比例（%）<Input type="number" min={0} max={100} value={ratio} onChange={e=>setRatio(Number(e.target.value))}/></label></div><div className="mix-bar"><span style={{width:`${Math.min(100,Math.max(0,ratio))}%`}}/></div><div className="mix-label"><span>旧词 {ratio}%</span><span>新词 {100-ratio}%</span></div><div className="range-label">原始编号范围</div><div className="form-row"><Input aria-label="起始编号" type="number" min={1} max={5640} value={start} onChange={e=>setStart(Number(e.target.value))}/><span>至</span><Input aria-label="结束编号" type="number" min={start} max={5640} value={end} onChange={e=>setEnd(Number(e.target.value))}/></div><Button variant="outline" className="full" onClick={choose} disabled={busy||!data}><Shuffle size={16}/> 按比例重新选词</Button><p className="selection-tip">首轮全用新词；旧词优先选待复习、覆盖轮数少的词，同等轮数先选较久未见的词。已掌握词不自动入选。</p><div className="selected-heading"><b>本次已选 <span>{selected.length}</span></b><button onClick={()=>{setTab('vocabulary');setFilter('all');setPage(0);}}>手动调整 <ArrowRight size={14}/></button></div><div className="chips">{selectedWords.map(w=><button key={w.id} className={w.occurrences?'chip old':'chip'} title={`${w.meaning} · 点击移除`} onClick={()=>toggle(w.id,false)}>{w.word}<X size={11}/></button>)}{!selected.length&&<p>先选词，再开始生成。</p>}</div><p className="actual-mix">实际：{oldCount} 旧词 + {selected.length-oldCount} 新词 · 约 {Math.ceil(selected.length/10)} 篇</p><Button className="full generate" onClick={()=>generate()} disabled={busy||generating||!selected.length||selected.length>90||!data}>{generating?<LoaderCircle className="spin"/>:<BookOpen size={17}/>} {generating?'有一轮正在生成':'生成新一轮'}<ArrowRight size={16}/></Button><p className="api-note">点击生成会调用你配置的 API。每篇单独请求；失败后不自动重试。</p></aside>
      </div>
     </TabsContent>
     <TabsContent value="vocabulary">
      <section className="vocab-panel"><div className="section-heading"><div><h2>词库与学习状态</h2><p className="subtitle">出现次数不等于掌握。这里分别记录提交、正文出现和覆盖轮数。</p></div><Button onClick={()=>{setTab('reading');setActiveId('');}}>使用已选 {selected.length} 词 <ArrowRight/></Button></div><div className="vocab-toolbar"><div className="search-box"><Search size={17}/><Input placeholder="搜索单词、释义或原始编号" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} aria-label="搜索词库"/></div><Choice label="筛选词汇状态" value={filter} onChange={v=>{setFilter(v);setPage(0);}} options={[["all","全部词条"],["new","未练习"],["seen","已接触"],["review","待复习"],["mastered","已掌握"],["pending","待核对"],["selected","本次已选"]]}/><Button variant="outline" onClick={()=>setSelected([])}>清空选词</Button></div><div className="vocab-notice"><CircleHelp size={16}/><span>待核对条目保留扫描原文，补全并确认后才能入选。正文匹配以完整词形为准，支持词表列出的拼写变体，不推测词根或变形。</span></div><Table><TableHeader><TableRow><TableHead>选词</TableHead><TableHead>编号 / 单词</TableHead><TableHead>中文释义</TableHead><TableHead>状态</TableHead><TableHead>提交</TableHead><TableHead>出现</TableHead><TableHead>轮数</TableHead><TableHead>最近接触</TableHead></TableRow></TableHeader><TableBody>{visible.slice(page*40,page*40+40).map(w=><TableRow key={w.id}><TableCell><Checkbox aria-label={`选择 ${w.word||w.id}`} checked={selected.includes(w.id)} disabled={w.review||(!selected.includes(w.id)&&selected.length>=90)} onCheckedChange={v=>toggle(w.id,!!v)}/></TableCell><TableCell><small className="word-id">{w.id}</small><button className="word-button" onClick={()=>{setEditing(w);setEditWord(w.word);setEditMeaning(w.meaning);}}>{w.word||'未识别'}{w.review&&<AlertCircle size={13}/>}</button></TableCell><TableCell className="meaning-cell">{w.meaning||'释义待核对'}</TableCell><TableCell>{w.review?<button className="badge amber" onClick={()=>{setEditing(w);setEditWord(w.word);setEditMeaning(w.meaning);}}>待核对</button>:<Choice value={w.status} label={`${w.word} 学习状态`} onChange={s=>wordState(w,s)} options={Object.entries(statuses)}/>}</TableCell><TableCell>{w.selectedCount}</TableCell><TableCell><b className={w.occurrences?'blue':''}>{w.occurrences}</b></TableCell><TableCell>{w.roundCount}</TableCell><TableCell>{w.lastSeen?new Date(w.lastSeen).toLocaleDateString('zh-CN'):'—'}</TableCell></TableRow>)}</TableBody></Table>{!visible.length&&<p className="no-results">没有匹配的词条，试试调整搜索或状态。</p>}<div className="pagination"><span>共 {visible.length} 条 · 已选 {selected.length} 词</span><div><Button variant="outline" disabled={page===0} onClick={()=>setPage(p=>p-1)}>上一页</Button><span>{page+1} / {Math.max(1,Math.ceil(visible.length/40))}</span><Button variant="outline" disabled={(page+1)*40>=visible.length} onClick={()=>setPage(p=>p+1)}>下一页</Button></div></div></section>
     </TabsContent>
    </Tabs>
    <footer className="main-footer">阅读 → 抄写 → 新语境复习 <span>本地保存 · 自己的节奏</span></footer>
   </main>
  </div>
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="config-dialog"><DialogHeader><DialogTitle>连接你的 API</DialogTitle><DialogDescription>使用 DeepSeek 或兼容 Chat Completions 的接口。Key 只保存在本机服务文件中，不写入前端或学习档案导出。</DialogDescription></DialogHeader>{error&&<p className="message error" role="alert">{error}</p>}<label>API Base URL<Input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://api.deepseek.com"/></label><label>模型名称<Input value={model} onChange={e=>setModel(e.target.value)} placeholder="填写服务商提供的模型名称"/></label><label>API Key<Input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={data?.config.hasKey?'已保存；留空保留原 Key':'粘贴你的 API Key'}/></label><p className="selection-tip">只填写 Base URL，不含 /chat/completions。保存不会发起生成请求。API 服务商按你的账户计费。</p><div className="dialog-actions">{data?.config.hasKey&&<Button variant="outline" disabled={busy} onClick={()=>run(async()=>{await api('config',{baseUrl,model,clearKey:true});setKey('');await refresh();setNotice('已移除本机保存的 API Key。');setSettings(false);})}>移除 Key</Button>}<Button disabled={busy} onClick={()=>run(async()=>{await api('config',{baseUrl,model,apiKey:key});setKey('');await refresh();setSettings(false);setNotice('配置已保存。选择词汇后即可生成短文。');})}>保存配置</Button></div></DialogContent></Dialog>
  <Dialog open={!!editing} onOpenChange={o=>!o&&setEditing(null)}><DialogContent className="config-dialog"><DialogHeader><DialogTitle>核对词条 · {editing?.id}</DialogTitle><DialogDescription>修改用于后续练习。已经生成的轮次保留当时的词表快照。</DialogDescription></DialogHeader>{error&&<p className="message error" role="alert">{error}</p>}<label>英文词形<Input value={editWord} onChange={e=>setEditWord(e.target.value)}/></label><label>中文释义<Textarea value={editMeaning} onChange={e=>setEditMeaning(e.target.value)}/></label><details><summary>查看扫描文本</summary><pre className="source-raw">{editing?.raw}</pre></details><Button disabled={busy||generating} onClick={()=>run(async()=>{await api('word',{id:editing?.id,word:editWord,meaning:editMeaning});await refresh();setEditing(null);setNotice('词条已核对，可用于后续练习。');})}>确认词条并保存</Button></DialogContent></Dialog>
 </div>;
}
