'use client';
import {useState} from 'react';
import ReadingPractice from '@/components/reading-practice';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
export type Retelling={id:string;original:string;transcript:string;confirmedTranscript:string;audioUrl:string;createdAt:string;aiStatus?:string;assessment?:{score:number;meaning:number;language:number;organization:number;feedback:string;strengths:string;missing:string;nextStep:string;improvedRetelling:string}};
function Feedback({attempt:a}:{attempt:Retelling}){const r=a.assessment;return <div className="coach-item">{r&&<><h4>{r.score} / 100 · AI 复述评分</h4><p>内容理解 {r.meaning}/60 · 语言表达 {r.language}/25 · 组织清楚 {r.organization}/15</p><p>{r.feedback}</p><p><strong>做得好：</strong>{r.strengths}</p><p><strong>遗漏或偏差：</strong>{r.missing}</p><p><strong>下一次：</strong>{r.nextStep}</p><details><summary>参考改述</summary><p lang="en">{r.improvedRetelling}</p></details></>}<details><summary>查看评分原文与提交文本</summary><p><strong>原文</strong></p><p lang="en">{a.original}</p><p><strong>提交给 AI 的复述</strong></p><p lang="en">{a.confirmedTranscript}</p><p><strong>最初识别文本</strong></p><p lang="en">{a.transcript||'未识别到英语'}</p></details></div>;}
export default function RetellingPractice({articleId,sourceId,original,hint:initialHint,history=[],onSaved}:{articleId:string;sourceId?:string;original:string;hint?:string;history?:Retelling[];onSaved:()=>Promise<unknown>}){
 const [hint,setHint]=useState(initialHint||''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[attempt,setAttempt]=useState<Retelling|null>(history.at(-1)||null),[text,setText]=useState(history.at(-1)?.confirmedTranscript||'');
 async function request(path:string,body:object){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Local-App':'vocab'},body:JSON.stringify({articleId,sourceId,...body})});const v=await r.json() as {error?:string};if(!r.ok)throw Error(v.error||'请求失败');return v;}
 async function getHint(){setBusy('hint');setError('');try{const v=await request('retell-hint',{}) as {hint:string};setHint(v.hint);await onSaved();}catch(e){setError(e instanceof Error?e.message:'提示生成失败');}finally{setBusy('');}}
 async function score(){if(!attempt)return;setBusy('score');setError('');try{const v=await request('retell-score',{recordingId:attempt.id,transcript:text}) as Retelling;setAttempt(v);await onSaved();}catch(e){setError(e instanceof Error?e.message:'评分失败');}finally{setBusy('');}}
 return <details className="retelling-practice"><summary>{sourceId?'本人复述这条语料':'本人复述这篇短文'}</summary><p>听懂后，用自己的英语说出意思，可先收起原文。允许同义改写，不要求逐字背诵。</p><details><summary>查看原文（评分时会一并附上）</summary><p lang="en">{original}</p></details><details><summary>中文提示</summary>{hint?<p style={{whiteSpace:'pre-line'}}>{hint}</p>:<Button variant="outline" onClick={getHint} disabled={!!busy}>{busy==='hint'?'正在生成…':'生成中文提示（调用现有 API）'}</Button>}</details>
 <ReadingPractice articleId={articleId} sourceId={sourceId} history={[]} onSaved={onSaved} onRecorded={r=>{const v=r as unknown as Retelling;setAttempt(v);setText(v.confirmedTranscript||v.transcript);setError('');}}/>
 {attempt&&!attempt.assessment&&<div><label htmlFor={'retell-'+articleId+(sourceId||'')}>确认识别文本（只修正识别错误，保留自己的表达）</label><Textarea id={'retell-'+articleId+(sourceId||'')} value={text} disabled={!!busy} onChange={e=>setText(e.target.value)} rows={5}/><p>提交时会将上面的原文和此处复述文本发送到你已配置的 API。评分不包含发音评价。</p>{attempt.aiStatus==='unconfirmed'&&<p>上次请求未确认完成，重新提交可能产生额外用量。</p>}<Button disabled={!!busy||!text.trim()} onClick={score}>{busy==='score'?'AI 正在评分…':'附上原文，提交 AI 评分'}</Button><audio controls preload="none" src={attempt.audioUrl} className="article-audio" aria-label="回听待评分复述"/></div>}
 {error&&<p role="alert">{error}</p>}{attempt?.assessment&&<Feedback attempt={attempt}/>}
 {history.length>0&&<details><summary>历次复述记录（{history.length} 次）</summary>{history.slice().reverse().map(a=><div key={a.id}><p>{new Date(a.createdAt).toLocaleString('zh-CN')} · {a.assessment?`${a.assessment.score} 分`:'待确认 / 待评分'}</p>{!a.assessment&&<Button variant="outline" onClick={()=>{setAttempt(a);setText(a.confirmedTranscript||a.transcript);}}>继续这次复述</Button>}<audio controls preload="none" src={a.audioUrl} className="article-audio" aria-label="回听历史复述"/><Feedback attempt={a}/></div>)}</details>}
 </details>;
}
